### PR TITLE
Update en_us.json

### PR DESCRIPTION
**Pull request by WakerPT**
Some very minor fixes from my previous commit.
Apologies 🙏

### CODE REVIEW

**Comment by Bluemangoo** [comment]
can u check typos in another open pr? thx.

**Comment by WakerPT** [comment]
> can u check typos in another open pr in ui repo? thx.

Tried to look at the EN localization of your PR, but I don't have permissions to commit to your branch.
I'm somewhat new to GitHub so I might be doing something wrong, should I fork your repo and PR from there?

Either way I've got the strings translated (to be honest not much needed to be changed).


Cheers!

**Comment by Bluemangoo** [comment]
> Tried to look at the EN localization of your PR, but I don't have permissions to commit to your branch. I'm somewhat new to GitHub so I might be doing something wrong, should I fork your repo and PR from there?
> 
> Either way I've got the strings translated (to be honest not much needed to be changed).
> 
> Cheers!

I'll be appreciated if you can fork and pull request😊

**Comment by Bluemangoo** [comment]
@WakerPT :

> > Tried to look at the EN localization of your PR, but I don't have permissions to commit to your branch. I'm somewhat new to GitHub so I might be doing something wrong, should I fork your repo and PR from there?
> > Either way I've got the strings translated (to be honest not much needed to be changed).
> > Cheers!
> 
> I'll be appreciated if you can fork and pull request😊

Plus, you can also fork, commit and push only, I can merge your commit with a link to your commit.

Anyway, as long as you commit and push it to GitHub, I'll merge your work in some way.

Please feel free to reply under this issue, mention me under your commit or pull request in my fork if you have an update.

Have a nice day, Thank you.

**Pull request merged**
